name: Build Angular App

on:
  push:
    branches:
      - main  # Uruchamia workflow przy pushu do głównej gałęzi
  pull_request:
    branches:
      - main  # Uruchamia workflow na PR do głównej gałęzi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # Cache'uje zależności npm dla szybszego budowania

      - name: Install dependencies
        run: npm ci  # Szybsza i czystsza alternatywa dla `npm install`

      - name: Build Angular app
        run: npm run build -- --configuration=production  # Buduje aplikację Angular w trybie produkcyjnym

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/  # Przechowuje artefakty budowania (np. do późniejszego deployu)
