name: Build Angular App

on:
  push:
    branches:
      - main  # Uruchamia workflow przy pushu do głównej gałęzi
  pull_request:
    branches:
      - main  # Uruchamia workflow na PR do głównej gałęzi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'  # Cache'uje zależności npm dla szybszego budowania
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend  # Przechodzimy do katalogu z aplikacją
          npm ci


      - name: Build Angular app
        run: |
          cd frontend
          npm run build -- --configuration=production  # Budujemy aplikację

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/  # Przechowuje artefakty budowania (np. do późniejszego deployu)
